<a href="https://colab.research.google.com/github/Vasavi708/DL_NN/blob/main/DL_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pan
import numpy as num

In [5]:
from tensorflow.keras.layers import Dense

In [7]:
!pip install tensorflow

     |████████████████████████████████| 462 kB 5.1 MB/s 


In [8]:
from tensorflow.keras.models import Sequential

In [9]:
from tensorflow.keras.utils import to_categorical

In [10]:
from sklearn.datasets import load_iris

In [11]:
data = load_iris()

In [12]:
features = data['data']
classes = data['target']

In [104]:
classes


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [74]:
target = to_categorical(classes, num_classes = 3)
target

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [22]:
classes.shape
features.shape
features.shape[1]

4

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test = train_test_split(features,target)
x_train,x_val,y_train,y_val = train_test_split(x_train,y_train)

In [26]:
model = Sequential()

In [33]:
model.add(Dense(300,input_shape = (features.shape[1],)))
model.add(Dense(100,activation = 'relu'))
model.add(Dense(50,activation = 'relu'))
model.add(Dense(30, activation = 'relu'))
model.add(Dense(15,activation = 'relu'))
model.add(Dense(3,activation = 'softmax'))


In [35]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 100)               500       
                                                                 
 dense_3 (Dense)             (None, 300)               30300     
                                                                 
 dense_5 (Dense)             (None, 300)               90300     
                                                                 
 dense_6 (Dense)             (None, 300)               90300     
                                                                 
 dense_7 (Dense)             (None, 100)               30100     
                                                                 
 dense_8 (Dense)             (None, 50)                5050      
                                                                 
 dense_9 (Dense)             (None, 30)                1

In [41]:
import tensorflow
model.compile(optimizer = 'sgd', loss = tensorflow.keras.losses.CategoricalCrossentropy(),
              metrics = ['accuracy'])

In [43]:
model.fit(x_train,y_train,epochs=50,validation_data = (x_val,y_val))

Epoch 1/50
3/3 [==============================] - 2s 196ms/step - loss: 1.0103 - accuracy: 0.2738 - val_loss: 1.1004 - val_accuracy: 0.1429
Epoch 2/50
3/3 [==============================] - 0s 28ms/step - loss: 1.0019 - accuracy: 0.4286 - val_loss: 1.0710 - val_accuracy: 0.1429
Epoch 3/50
3/3 [==============================] - 0s 25ms/step - loss: 0.8993 - accuracy: 0.4286 - val_loss: 1.1022 - val_accuracy: 0.4286
Epoch 4/50
3/3 [==============================] - 0s 27ms/step - loss: 0.9018 - accuracy: 0.3929 - val_loss: 0.9838 - val_accuracy: 0.1429
Epoch 5/50
3/3 [==============================] - 0s 35ms/step - loss: 0.8421 - accuracy: 0.4405 - val_loss: 1.0092 - val_accuracy: 0.1429
Epoch 6/50
3/3 [==============================] - 0s 27ms/step - loss: 0.8221 - accuracy: 0.4286 - val_loss: 0.8833 - val_accuracy: 0.6786
Epoch 7/50
3/3 [==============================] - 0s 35ms/step - loss: 0.8310 - accuracy: 0.7024 - val_loss: 0.8808 - val_accuracy: 0.3571
Epoch 8/50
3/3 [==========

In [79]:
y_pred = model.predict(x_test)
y_pred
y_pred_ =num.argmax(y_pred,axis = 1)
print(y_pred_)
y_pred_1 = []
for i in y_pred:
  y_pred_1.append(num.argmax(i))
y_pred_1

[0 2 1 0 2 0 2 0 1 1 1 1 1 0 0 1 2 0 1 0 1 0 0 2 2 1 0 1 2 1 0 1 1 0 0 2 2
 0]


[0,
 2,
 1,
 0,
 2,
 0,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 2,
 0,
 1,
 0,
 1,
 0,
 0,
 2,
 2,
 1,
 0,
 1,
 2,
 1,
 0,
 1,
 1,
 0,
 0,
 2,
 2,
 0]

In [53]:
from sklearn.metrics import accuracy_score

In [65]:
y_test_ = []
for i in y_test:
  y_test_.append(num.argmax(i))
y_test_  


[0,
 2,
 1,
 0,
 2,
 0,
 2,
 0,
 2,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 2,
 0,
 1,
 0,
 1,
 0,
 0,
 2,
 2,
 1,
 0,
 1,
 2,
 1,
 0,
 1,
 1,
 0,
 0,
 2,
 2,
 0]

In [67]:
accuracy_score(y_test_,y_pred_)

0.9736842105263158

Preprocessing Code


In [72]:
model.save("DL_NN.h5")

In [73]:
from tensorflow.keras.models import load_model

In [75]:
model = load_model("./DL_NN.h5")

In [91]:
new = [0.5,0.65,0.45,0.66]
y_prediction = model.predict([[0.5,0.65,0.45,0.66]])
y_prediction


array([[0.25870168, 0.36323267, 0.3780656 ]], dtype=float32)

In [92]:
clas = num.argmax(y_prediction)
clas

2

In [94]:
#final_ypred = num.insert(y_pred_,2,clas)
#final_ypred
'''final_ypred = num.concatenate((y_pred_,[clas]))
final_ypred'''
final_ypred = num.append(y_pred_,clas)
final_ypred

array([0, 2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 1, 0,
       0, 2, 2, 1, 0, 1, 2, 1, 0, 1, 1, 0, 0, 2, 2, 0, 2])

In [105]:
final_features = num.concatenate((features,[new]))
final_features

array([[5.1 , 3.5 , 1.4 , 0.2 ],
       [4.9 , 3.  , 1.4 , 0.2 ],
       [4.7 , 3.2 , 1.3 , 0.2 ],
       [4.6 , 3.1 , 1.5 , 0.2 ],
       [5.  , 3.6 , 1.4 , 0.2 ],
       [5.4 , 3.9 , 1.7 , 0.4 ],
       [4.6 , 3.4 , 1.4 , 0.3 ],
       [5.  , 3.4 , 1.5 , 0.2 ],
       [4.4 , 2.9 , 1.4 , 0.2 ],
       [4.9 , 3.1 , 1.5 , 0.1 ],
       [5.4 , 3.7 , 1.5 , 0.2 ],
       [4.8 , 3.4 , 1.6 , 0.2 ],
       [4.8 , 3.  , 1.4 , 0.1 ],
       [4.3 , 3.  , 1.1 , 0.1 ],
       [5.8 , 4.  , 1.2 , 0.2 ],
       [5.7 , 4.4 , 1.5 , 0.4 ],
       [5.4 , 3.9 , 1.3 , 0.4 ],
       [5.1 , 3.5 , 1.4 , 0.3 ],
       [5.7 , 3.8 , 1.7 , 0.3 ],
       [5.1 , 3.8 , 1.5 , 0.3 ],
       [5.4 , 3.4 , 1.7 , 0.2 ],
       [5.1 , 3.7 , 1.5 , 0.4 ],
       [4.6 , 3.6 , 1.  , 0.2 ],
       [5.1 , 3.3 , 1.7 , 0.5 ],
       [4.8 , 3.4 , 1.9 , 0.2 ],
       [5.  , 3.  , 1.6 , 0.2 ],
       [5.  , 3.4 , 1.6 , 0.4 ],
       [5.2 , 3.5 , 1.5 , 0.2 ],
       [5.2 , 3.4 , 1.4 , 0.2 ],
       [4.7 , 3.2 , 1.6 , 0.2 ],
       [4.

In [ ]:
''' we can use the 'final_features' and 'clas' to pass through 
whole process and generate accuracy_score'''